###################################
# Turn on ZSH VI mode
bindkey -v
export KEYTIMEOUT=1

# Yank selected buffer to Clipboard in VI Mode
function vi-yank-wl {
  zle vi-yank
  echo "$CUTBUFFER" | wl-copy
}
zle -N vi-yank-wl
bindkey -M vicmd 'y' vi-yank-wl

# Set keybindings to vi
zstyle ':prezto:module:editor' key-bindings 'vi'

# Turn down direnv verbosity
export DIRENV_LOG_FORMAT=''
###################################