{
  imports = [
    ./bat.nix
    ./btop.nix
    ./direnv.nix
    ./flameshot.nix
    ./foot.nix
    ./fzf.nix
    ./ghostty.nix
    ./git.nix
    ./gpg.nix
    ./gsettings.nix
    ./gtk.nix
    ./hyprcursor.nix
    ./k9s.nix
    ./kind.nix
    ./lazydocker.nix
    ./lazygit.nix
    ./lsd.nix
    ./obs.nix
    ./ohmyposh.nix
    ./rofi.nix
    ./spicetify.nix
    ./ssh.nix
    ./sway.nix
    ./tealdeer.nix
    ./tmux.nix
    ./waybar.nix
    ./wezterm.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
